pipeline:
  test:
    image: rust:1.25-stretch
    commands:
      - cargo test
    when:
      event: pull_request
  build:
    image: rust:1.25-stretch
    commands:
      - cargo install cargo-watch
      - cargo build --release --locked
    when:
      event: push
  package:
    image: plugins/docker
    repo: storiqateam/stq-gw
    tags:
      - ${DRONE_BRANCH/\//_}
      - ${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
    username: stqcommon
    password: "Tz-q6qDL#d3Mz8hm"
    dockerfile: docker/Dockerfile.run
    when:
      event: [ push, tag ]
  cleanup:
    image: rust:1.25-stretch
    commands:
      - cargo clean
  deploy2nightly:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: https://api.nightly.stq.cloud
    kubernetes_token: 32txou6YhrlD3sHcpxsiCmP1m7taE1fY
    namespace: default
    deployment: gateway
    repo: storiqateam/stq-gw
    container: gateway
    tag: ${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
    when:
      branch: master
      event: push
  test_release:
    image: jackthestripper/drone_k8s_rollout_test:2018042301
    user: admin
    token: 32txou6YhrlD3sHcpxsiCmP1m7taE1fY
    addr: https://api.nightly.stq.cloud
    object: gateway
    kind: deployment
    ca: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJ1Z0F3SUJBZ0lNRlNTbzZ4bytxYmxYWFVweU1BMEdDU3FHU0liM0RRRUJDd1VBTUJVeEV6QVIKQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13SGhjTk1UZ3dOREV3TVRBeE9ESXhXaGNOTWpnd05EQTVNVEF4T0RJeApXakFWTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQXdDZlhvZmIwMHQ2ZG9xMm1MZzlreUxjTE5lTEYzVlM0R29lRUNOMCtuaityall1THRaYlkKOStiV0JBMW1Ua3NWS3JGcUFob2l5K1g0dkRzYWcyWmExMm80cVlRci9FWGs2cVRtRnluT0s1NkpLdWJoVXNoRAp3QjQxTDgvaXJ1NmdNUWs2a2lYbnVuN2UzS25iemJlZml5QytVc2I5TFR4UWRPMldvTm5tQVpZV2g3QjR4YUJmCm5vSGRHZE4wQTBwZlNBZU1SYWZjb0M3QmNyQldiQlUzMG4xMlM3bFdUTkl0OU82SWMwVUt2NzFXTFlDeFNOQm8KSGhkaEZzZzlaWjQ4dVBPQkRzRlBxUXFsTUdtWEtUVW1ydS8zTG1qSnRFV1h5WVJ0QjJvOVlreGdTUUV4Yi9FZwpIdjNGQ1dYblY2NVNDUTRnQTZHL2tINUV4N1hoMnlybGh3SURBUUFCb3lNd0lUQU9CZ05WSFE4QkFmOEVCQU1DCkFRWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFjWkVIMEc4enFmU2QKR1Q5RDMraVVDdnl5akxrY2xLUjhRWENEVGdxVXB3TGNaN0FuUU1uN2xkalk0UjJHR3lnMnZteWkyZ1AzbktxRQpPWldGTk5WYjUxOHkyN3c2bXdTUnVuUHZ1VzdzT0NFS2I3MmhzN1dFZUNVUGZ3Ni9kVUFueDNzVW1CV243RzVTCjhBRjBvc0lQZVNzeXhVZnNpc25ucG43MGVuRHdtV3k3SzdhYXJvb3hFNk0zMDhNWFROeGh0bW9SOVFPQzR3QUgKWk80SzM0eFpLK2xoTHZNcFpZSHVyeEZUZFJiR3JhTHNKVjZ6YlRHdURlSTAwckY3MVdhMHJlUkF0NVZ6TEgyNwppclJMUlRZVFphQmpuTHlrcGVYbGw3eEFnamxpWVM1L3B1RHZsMFk0elBxMFI4U3NjYXRtUTB0SnVIa2tQaElkCktXalVlMjM2TFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    when:
      branch: master
      event: push
  deploy2stable:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: https://api.stable.stq.cloud
    kubernetes_token: vhkzUYmnPSI7MtJO3Et9KczuGoS0goqV
    namespace: default
    deployment: gateway
    repo: storiqateam/stq-gw
    container: gateway
    tag: ${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
    when:
      branch: master
      event: push
    when:
      branch: master
      event: push
  deploy2stage:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: https://api.stage.stq.cloud
    kubernetes_token: PW2clI0vKqLi3eywlN776rMyE7hk1pgX
    namespace: default
    deployment: gateway
    repo: storiqateam/stq-gw
    container: gateway
    tag: ${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
    when:
      branch: release*
      event: push
  notify_slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: back
    icon_url: https://drone.io/favicon.ico
    username: cd.stq.cloud
    template: >
      {{#success build.status}}
        Build {{build.number}} for {{repo.name}} branch {{build.branch}} succeeded.
      {{else}}
        Build {{build.number}} for {{repo.name}} branch {{build.branch}} failed.
      {{/success}}
    when:
      event: push
      status:  [ failure, success ]
