pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./target/release
    volumes:
      - /tmp/cache:/cache
  build:
    image: rust:1.24.1-stretch
    commands:
      - cargo install cargo-watch
      - cargo build --release --locked
    volumes:
      - /mnt:/mnt
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./target/release
    volumes:
      - /tmp/cache:/cache
  package:
    image: plugins/docker
    repo: storiqateam/stq-gw
    tags:
      - ${DRONE_BRANCH}
      - ${DRONE_BRANCH}${DRONE_BUILD_NUMBER}
    secrets: [ dockerhub_user, dockerhub_pass ]
    dockerfile: docker/Dockerfile.run
    volumes:
      - /mnt:/mnt
  #deploy:
    #image: quay.io/honestbee/drone-kubernetes
    #kubernetes_server: https://api.stage.stq.cloud
    #kubernetes_token: ${k8s_token}
    #namespace: default
    #deployment: gateway
    #repo: storiqateam/stq-gw
    #container: gateway
    #tag: ${DRONE_BRANCH}${DRONE_BUILD_NUMBER}
