pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./target/deps
    volumes:
      - /tmp/cache:/cache
  build:
    image: rust:1.24.1-stretch
    commands:
      - cargo install cargo-watch
      - cargo build --release --locked
    volumes:
      - /mnt:/mnt
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./target/deps
    volumes:
      - /tmp/cache:/cache
  package:
    image: plugins/docker
    repo: storiqateam/stq-gw
    tags:
      - ${DRONE_BRANCH}
      - ${DRONE_BRANCH}${DRONE_BUILD_NUMBER}
    dockerfile: docker/Dockerfile.run
    volumes:
      - /mnt:/mnt
