pipeline:
  build:
    image: rust:1.24.1-stretch
    commands:
      - cargo install cargo-watch
      - cargo build --release --locked
    volumes:
      - /mnt:/mnt
  package:
    image: plugins/docker
    repo: storiqateam/stq-gw
    tags:
      - $DRONE_BRANCH
      - ${DRONE_BRANCH}${DRONE_BUILD_NUMBER}
    dockerfile: docker/Dockerfile.run
    volumes:
      - /mnt:/mnt
