pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./target/release
    volumes:
      - /tmp/cache:/cache
  build:
    image: rust:1.24.1-stretch
    commands:
      - cargo install cargo-watch
      - cargo build --release --locked
    volumes:
      - /mnt:/mnt
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./target/release
    volumes:
      - /tmp/cache:/cache
  package:
    image: plugins/docker
    repo: storiqateam/stq-gw
    tags:
      - ${DRONE_BRANCH}
      - ${DRONE_BRANCH}${DRONE_BUILD_NUMBER}
    username: stqcommon
    password: "Tz-q6qDL#d3Mz8hm"
    dockerfile: docker/Dockerfile.run
    volumes:
      - /mnt:/mnt
  deploy2stage:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: https://api.stage.stq.cloud
    kubernetes_token: PW2clI0vKqLi3eywlN776rMyE7hk1pgX
    namespace: default
    deployment: gateway
    repo: storiqateam/stq-gw
    container: gateway
    tag: ${DRONE_BRANCH}${DRONE_BUILD_NUMBER}
    when:
      branch: [master, stage]
  notify_slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: back
    icon_url: https://drone.io/favicon.ico
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
