[package]
name = "gateway"
version = "0.1.0"
authors = ["root"]

[lib]
name = "gateway_lib"
path = "src/lib.rs"

[[bin]]
name = "gateway_runner"
path = "src/main.rs"



[dependencies]
juniper = "0.9.0"
juniper_rocket = "0.1.0"
rocket = "0.3.3"
rocket_codegen = "0.3.3"
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
