[package]
name = "gateway"
version = "0.1.0"
authors = ["root"]

[lib]
name = "gateway_lib"
path = "src/lib.rs"

[[bin]]
name = "gateway_runner"
path = "src/main.rs"

[[test]]
name = "tests"
path = "tests/lib.rs"

[dependencies]
juniper = "0.9.0"
hyper = "0.11.9"
futures = "0.1.17"