version: '3'
services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: gateway
    working_dir: /app
    command: cargo run
    volumes:
      - ..:/app
      - stq_cargo_cache:/usr/local/cargo
    environment:
      - "RUST_LOG=gateway=debug"
    ports:
      - 8000:8000
    stdin_open: true

volumes:
  stq_cargo_cache:

networks:
  default:
    external:
      name: storiqa
