[gateway]
url="0.0.0.0:8000"
graphql_thread_pool_size=3
http_client_buffer_size=3
http_client_retries=3

[users_microservice]
url="http://users:8000"

[store_microservice]
url="http://localhost:8001"

[orders_microservice]
url="http://localhost:8002"

[billing_microservice]
url="http://localhost:8003"
