[gateway]
url="0.0.0.0:8000"
graphql_thread_pool_size=3
http_client_buffer_size=3
http_client_retries=3
records_limit=100

[users_microservice]
url="http://users:8000"

[stores_microservice]
url="http://stores:8001"

[orders_microservice]
url="http://orders:8002"

[billing_microservice]
url="http://billing:8003"

[saga_microservice]
url="http://saga:8004"

[warehouses_microservice]
url="http://warehouses:8005"
