[jwt]
public_key_path = "config/keys/public_key.der"
leeway = 86400

[cors]
domain = "http://localhost:3003"
max_age = "86400"

[graylog]
addr = "udplog.stq.cloud:32303"

[gateway]
url="0.0.0.0:8000"
graphql_thread_pool_size=1
http_client_buffer_size=1
http_client_retries=1
records_limit=100
http_timeout_ms=15000

[users_microservice]
url="http://users:8000"

[stores_microservice]
url="http://stores:8000"

[orders_microservice]
url="http://orders:8000"

[billing_microservice]
url="http://billing:8000"

[saga_microservice]
url="http://saga:8000"

[warehouses_microservice]
url="http://warehouses:8000"

[notifications_microservice]
url="http://notifications:8000"

[delivery_microservice]
url="http://delivery:8000"
